package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TotalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTotalAllPropertiesEquals(Total expected, Total actual) {
        assertTotalAutoGeneratedPropertiesEquals(expected, actual);
        assertTotalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTotalAllUpdatablePropertiesEquals(Total expected, Total actual) {
        assertTotalUpdatableFieldsEquals(expected, actual);
        assertTotalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTotalAutoGeneratedPropertiesEquals(Total expected, Total actual) {
        assertThat(actual)
            .as("Verify Total auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTotalUpdatableFieldsEquals(Total expected, Total actual) {
        assertThat(actual)
            .as("Verify Total relevant properties")
            .satisfies(a -> assertThat(a.getMedia()).as("check media").isEqualTo(expected.getMedia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTotalUpdatableRelationshipsEquals(Total expected, Total actual) {
        assertThat(actual)
            .as("Verify Total relationships")
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()));
    }
}
